import type { Database } from '@/types/cms';
import bcrypt from 'bcryptjs';

// Initial database with default admin user
const initialData: Database = {
    products: [
        {
            id: 'coway-150',
            name: 'Coway AirMega 150 (AP-1019C)',
            slug: 'coway-airmega-150',
            category: 'home',
            buyPrice: 12900,
            rentPrice: 499,
            buyAvailable: true,
            rentAvailable: true,
            description: 'The Coway AirMega 150 is a compact yet powerful air purifier, perfect for bedrooms and home offices. It features a Green True HEPA filter that traps 99.99% of allergens and pollutants.',
            features: ['True HEPA Filter', 'Cartridge Design', 'Real-time AQI'],
            specifications: { coverage: '355 sqft', cadr: '303 m³/h', power: '35W' },
            images: ['https://m.media-amazon.com/images/I/51HaE70EANL._SX679_.jpg'],
            altTexts: ['Coway AirMega 150'],
            seo: { metaTitle: 'Coway AirMega 150', metaDescription: 'Rent or Buy Coway AirMega 150 in India', h1: 'Coway AirMega 150', canonical: '', keywords: [] },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'philips-2000',
            name: 'Philips AC1215/20 Air Purifier',
            slug: 'philips-ac1215',
            category: 'home',
            buyPrice: 9999,
            rentPrice: 399,
            buyAvailable: true,
            rentAvailable: true,
            description: 'Intelligent sensing for professional-grade air quality. Purifies a standard room in just 12 minutes.',
            features: ['VitaShield IPS', 'AeraSense Technology', 'Night Mode'],
            specifications: { coverage: '270 sqft', cadr: '270 m³/h', power: '50W' },
            images: ['https://m.media-amazon.com/images/I/61y8L2aXk+L._SX679_.jpg'],
            altTexts: ['Philips Air Purifier'],
            seo: { metaTitle: 'Philips AC1215', metaDescription: 'Philips Air Purifier Rental India', h1: 'Philips AC1215', canonical: '', keywords: [] },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'dyson-tp03',
            name: 'Dyson Pure Cool Link Tower',
            slug: 'dyson-pure-cool-link-tp03',
            category: 'home',
            buyPrice: 29900,
            rentPrice: 1499,
            buyAvailable: true,
            rentAvailable: true,
            description: 'Automatically removes 99.95% of allergens and pollutants as small as 0.1 microns.',
            features: ['Air Multiplier Technology', 'App Control', 'Oscillation'],
            specifications: { coverage: '400 sqft', cadr: 'n/a', power: '40W' },
            images: ['https://m.media-amazon.com/images/I/61yOse4XjDL._SX679_.jpg'],
            altTexts: ['Dyson TP03'],
            seo: { metaTitle: 'Dyson Pure Cool Link', metaDescription: 'Rent Dyson Air Purifier', h1: 'Dyson Pure Cool Link', canonical: '', keywords: [] },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'cr-box-kit',
            name: 'Corsi-Rosenthal Box Kit (DIY)',
            slug: 'cr-box-kit-diy',
            category: 'diy',
            buyPrice: 2499,
            rentPrice: null,
            buyAvailable: true,
            rentAvailable: false,
            description: 'Everything you need to build your own high-performance air cleaner. Includes 4 MERV-13 filters, fan, and tape.',
            features: ['4x MERV-13 Filters', 'High Velocity Fan', 'Duct Tape Included'],
            specifications: { coverage: '500+ sqft', cadr: 'Estimated 400+ m³/h', power: '60W' },
            images: ['https://upload.wikimedia.org/wikipedia/commons/2/26/Corsi-Rosenthal_Box.jpg'],
            altTexts: ['Corsi-Rosenthal Box'],
            seo: { metaTitle: 'DIY Air Purifier Kit', metaDescription: 'Build your own air purifier', h1: 'DIY CR Box Kit', canonical: '', keywords: [] },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'diy-ready',
            name: 'Pre-Assembled DIY Unit',
            slug: 'diy-ready-unit',
            category: 'diy',
            buyPrice: 3499,
            rentPrice: null,
            buyAvailable: true,
            rentAvailable: false,
            description: 'A pre-built Corsi-Rosenthal box. High performance, low cost, ready to plug and play.',
            features: ['Pre-assembled', 'MERV-13 Filtration', 'High CADR'],
            specifications: { coverage: '500+ sqft', cadr: 'Estimated 400+ m³/h', power: '60W' },
            images: ['https://upload.wikimedia.org/wikipedia/commons/2/26/Corsi-Rosenthal_Box.jpg'],
            altTexts: ['Assembled CR Box'],
            seo: { metaTitle: 'Ready to use DIY Purifier', metaDescription: 'Cheap effective air purifier', h1: 'Pre-Assembled DIY Unit', canonical: '', keywords: [] },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'n95-mask-pack',
            name: 'N95 Anti-Pollution Masks (Pack of 5)',
            slug: 'n95-masks-5pack',
            category: 'prevention',
            buyPrice: 499,
            rentPrice: null,
            buyAvailable: true,
            rentAvailable: false,
            description: 'NIOSH certified N95 masks for superior protection against PM2.5.',
            features: ['5 Layers', 'Breathable', 'Adjustable Nose Clip'],
            specifications: { type: 'N95', quantity: '5' },
            images: ['https://m.media-amazon.com/images/I/71p+6jS0aJL._SX679_.jpg'],
            altTexts: ['N95 Masks'],
            seo: { metaTitle: 'N95 Masks India', metaDescription: 'Buy N95 Masks', h1: 'N95 Anti-Pollution Masks', canonical: '', keywords: [] },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'aqi-monitor',
            name: 'Portable AQI Monitor',
            slug: 'portable-aqi-monitor',
            category: 'prevention',
            buyPrice: 2999,
            rentPrice: 299,
            buyAvailable: true,
            rentAvailable: true,
            description: 'Accurate PM2.5 and PM10 laser sensor. Know what you breathe.',
            features: ['Laser Sensor', 'Rechargeable', 'LCD Display'],
            specifications: { range: '0-999 ug/m3', battery: '2000mAh' },
            images: ['https://m.media-amazon.com/images/I/61K-w1Ck+qL._SX679_.jpg'],
            altTexts: ['AQI Monitor'],
            seo: { metaTitle: 'Buy AQI Monitor', metaDescription: 'Air Quality Monitor India', h1: 'Portable AQI Monitor', canonical: '', keywords: [] },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'car-purifier-1',
            name: 'Antia Car Air Purifier Pro',
            slug: 'antia-car-purifier-pro',
            category: 'car',
            buyPrice: 3999,
            rentPrice: null,
            buyAvailable: true,
            rentAvailable: false,
            description: 'Compact high-efficiency air purifier designed for cars. Removes dust, smoke, and odors quickly.',
            features: ['HEPA Filter', 'Car Adapter', 'Silent Operation'],
            specifications: { coverage: 'Car Interior', cadr: '50 m³/h', power: '5W' },
            images: ['https://placehold.co/600x600/e2e8f0/475569?text=Car+Purifier'],
            altTexts: ['Car Purifier'],
            seo: { metaTitle: 'Car Air Purifier', metaDescription: 'Best car air purifier for pollution', h1: 'Antia Car Air Purifier', canonical: '', keywords: [] },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        }
    ],
    pages: [],
    menus: [
        {
            id: '1',
            name: 'Main Navigation',
            location: 'header',
            items: [
                {
                    id: '1', label: 'Air Purifiers', url: '/air-purifiers', type: 'dropdown', order: 1, children: [
                        { id: '1-1', label: 'Home', url: '/air-purifiers/home', type: 'internal', order: 1 },
                        { id: '1-2', label: 'Office', url: '/air-purifiers/office', type: 'internal', order: 2 },
                    ]
                },
                { id: '2', label: 'Filters & Accessories', url: '/filters', type: 'internal', order: 2 },
                { id: '3', label: 'Pollution Prevention', url: '/pollution-prevention', type: 'internal', order: 3 },
                { id: '4', label: 'DIY & Kits', url: '/diy-kits', type: 'internal', order: 4 },
                { id: '5', label: 'Blogs', url: '/blogs', type: 'internal', order: 5 },
                { id: '6', label: 'About Us', url: '/about', type: 'internal', order: 6 },
                { id: '7', label: 'Contact Us', url: '/contact', type: 'internal', order: 7 },
            ],
        },
    ],
    redirects: [],
    media: [],
    settings: {
        id: '1',
        globalHeadCode: '',
        globalBodyCode: '',
        siteName: 'PureAir',
        siteDescription: 'India\'s #1 Air Purifier Rental & Sales Service',
        defaultSEO: {
            metaTitle: 'PureAir - Buy & Rent Air Purifiers in India',
            metaDescription: 'Breathe pure air with India\'s #1 Air Purifier Rental & Sales service.',
            h1: 'Breathe Pure, Live Healthy',
            canonical: 'https://pureair.in',
            keywords: ['Air Purifier', 'Rent Air Purifier', 'Buy Air Purifier', 'India'],
        },
        favicon: '/favicon.ico',
        logo: '/logo.png',
    },
    customers: [],
    orders: [],
    users: [
        {
            id: '1',
            username: 'admin',
            // Password: Sunpower@11@24 (hashed)
            passwordHash: bcrypt.hashSync('Sunpower@11@24', 10),
            createdAt: new Date().toISOString(),
        },
    ],
};

export default initialData;
